#!/usr/bin/env python3

def inc(s, n=1):
    s = [ord(c)-ord('a') for c in reversed(s)]
    while n:
        i = 0
        while i < len(s):
            s[i] += 1
            if s[i] == 26:
                s[i] = 0
                i += 1
            else:
                break
        n -= 1
    return ''.join(chr(n+ord('a')) for n in reversed(s))

inc('hijklmmn')
